feature/HK-62: Header 컴포넌트 구현
team-dopamine/husk-web pull request #7
Opened 2024-11-22 14:41 UTC by juiuj

## Motivation

헤더 구현을 통해 사용자가 주요 기능에 빠르게 접근할 수 있도록 하였음.

## Problem Solving

- styled-components 패키지 설치
- `Header.tsx` 작성
- `Header-styled.tsx` 작성
- App.tsx 파일에 `<Header/>` 컴포넌트 삽입
- Ant Design 라이브러리 설치
- Ant Design 라이브러리 활용하여 Button 스타일링
## To Reviewer

로고 이미지 컨셉에 관해 이야기 나눠보면 좋을 것 같습니다~!

2024-11-22 16:31 UTC, jinlee1703 reviewed
확인했습니다. 코멘트로 의견 공유 해주시면 감사하겠습니다 :)

2024-11-22 16:31 UTC, jinlee1703 commented on src/components/Header.tsx
> +        <LoginBtn>Login</LoginBtn>
P3) 저번에 이야기했던 대로 [Ant Design](https://ant.design/components/button)이라는 프론트엔드 라이브러리 활용해보는 거 어떻게 생각하세요?

만약 쓰기 싫다면, 아무래도 버튼은 많이 쓰는 컴포넌트다보니 공통 컴포넌트를 추가로 구현해야할 것 같긴 한데..

2024-11-22 16:36 UTC, juiuj commented on src/components/Header.tsx
> +        <LoginBtn>Login</LoginBtn>
오 좋은 방법인 것 같습니다! Ant Design 사용하는 걸로 하고 추후에 버튼 디자인 관련해서 의논 필요할 것 같습니당

2024-11-22 16:40 UTC, jinlee1703 commented on src/components/Header.tsx
> +        <LoginBtn>Login</LoginBtn>
| Antd Examples |
|---|
| <img width="745" alt="image" src="https://github.com/user-attachments/assets/9c856e05-52a8-4a15-97cc-c46a444419e2"> |

넵, Primary Button이 가장 직관적이고, Link Button 형식이 가장 Figma와 유사한 것 같아 둘 중 주희님께서 선택해주시면 감사하겠습니다 :)

2024-11-22 18:29 UTC, juiuj commented on src/components/Header.tsx
> +        <LoginBtn>Login</LoginBtn>
![스크린샷 2024-11-23 오전 3 26 23](https://github.com/user-attachments/assets/dd07fae3-33db-48cc-9f89-1020b3109e27)
네! `Primary Button`으로 선택하여 ant design 관련 라이브러리 설치 후 버튼 스타일링 수정해 두었습니다!

2024-11-22 20:57 UTC, jinlee1703 requested changes
패키지 구조 설계 과정에서 혼동이 오는 부분이 있는데 코멘트 한번 부탁드리겠습니다!

2024-11-22 20:57 UTC, jinlee1703 commented on src/components/Header.tsx
> +import { HeaderWrapper, LogoWrapper, LogoImg, Logo, LoginButton } from '../styles/Header-styled';
P2) 저희 패키지 구조를 아래와 같이 결정했었는데요.

<img width="224" alt="image" src="https://github.com/user-attachments/assets/9af7872e-97db-413a-99cc-cc46c6fa1f54">

- `/components/Header.tsx` -> `compontents/header/index.tsx`
- `/styles/Hedader-styled.tsx` -> `compontents/header/index.style.tsx`

이렇게 바뀌어야 하는거 아니예요?? `styles` 패키지를 그 때 없애기로 결정했던 것 같은데 아닐까요?

2024-11-23 12:18 UTC, juiuj commented on src/components/Header.tsx
> +import { HeaderWrapper, LogoWrapper, LogoImg, Logo, LoginButton } from '../styles/Header-styled';
확인 후 컴포넌트 구조 변경 완료하였습니다:) 피드백 감사합니다!

2024-11-24 03:48 UTC, jinlee1703 approved these changes
확인했습니다! 고생하셨어요 :)

2024-11-24 05:23 UTC, merged